### ISSUE TITLE
请问大佬SandHook和Epic稳定性比起来如何

### ISSUE THREAD

**Issue by Anzhi-Meiying** [ganyao114/SandHook#10]

**Comment by Anzhi-Meiying** [comment]
另外我发现 hook 之后没反应

![image](https://user-images.githubusercontent.com/13428030/56876225-7e5aa400-6a78-11e9-8685-f2259d2ff35d.png)

毫无反应...但是 log 上面提示 hook 了

![image](https://user-images.githubusercontent.com/13428030/56876263-bfeb4f00-6a78-11e9-83ed-8b817b04dcdd.png)

> 系统是 8.1.0， MIUI10
手机是小米 Note3

@ganyao114

**Comment by Anzhi-Meiying** [comment]
当我在 AS 模拟器中用 Android P 测试时出现了这些 log：
![image](https://user-images.githubusercontent.com/13428030/56876352-5455b180-6a79-11e9-8aae-18fa46eca40d.png)


> 2019-04-29 12:20:10.532 3001-3001/? E/SandXposed: error occur when hook method <public android.content.pm.ApplicationInfo()>
    java.lang.NoClassDefFoundError: com.swift.sandhook.xposedcompat.hookstub.HookStubManager
        at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.getHookMethodEntity(HookStubManager.java:64)
        at com.swift.sandhook.xposedcompat.methodgen.DynamicBridge.hookMethod(DynamicBridge.java:62)
        at de.robv.android.xposed.XposedBridge.hookMethodNative(XposedBridge.java:275)
        at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:181)
        at de.robv.android.xposed.XposedBridge.hookAllConstructors(XposedBridge.java:237)
        at com.crystal.chat.hook.SafetyHooker.<init>(SafetyHooker.java:28)
        at com.crystal.chat.hook.MainHookApplication.attachBaseContext(MainHookApplication.java:61)
        at android.app.Application.attach(Application.java:212)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1121)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1061)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5842)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.crystal.chat-6Xom5tpjwmxgaBsFLCTcEA==/base.apk"],nativeLibraryDirectories=[/data/app/com.crystal.chat-6Xom5tpjwmxgaBsFLCTcEA==/lib/x86, /data/app/com.crystal.chat-6Xom5tpjwmxgaBsFLCTcEA==/base.apk!/lib/x86, /system/lib]]] couldn't find "libsandhook.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.swift.sandhook.SandHookConfig$1.loadLib(SandHookConfig.java:22)
        at com.swift.sandhook.SandHook.<clinit>(SandHook.java:48)
        at com.swift.sandhook.SandHook.is64Bit(Native Method)
        at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.<clinit>(HookStubManager.java:43)
        at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.getHookMethodEntity(HookStubManager.java:64)
        at com.swift.sandhook.xposedcompat.methodgen.DynamicBridge.hookMethod(DynamicBridge.java:62)
        at de.robv.android.xposed.XposedBridge.hookMethodNative(XposedBridge.java:275)
        at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:181)
        at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:187)
        at com.crystal.chat.hook.MainHookApplication.attachBaseContext(MainHookApplication.java:47)
        at android.app.Application.attach(Application.java:212) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1121) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1061) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5842) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by ganyao114** [comment]
> 当我在 AS 模拟器中用 Android P 测试时出现了这些 log：
> ![image](https://user-images.githubusercontent.com/13428030/56876352-5455b180-6a79-11e9-8aae-18fa46eca40d.png)
> 
> > 2019-04-29 12:20:10.532 3001-3001/? E/SandXposed: error occur when hook method <public android.content.pm.ApplicationInfo()>
> > java.lang.NoClassDefFoundError: com.swift.sandhook.xposedcompat.hookstub.HookStubManager
> > at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.getHookMethodEntity(HookStubManager.java:64)
> > at com.swift.sandhook.xposedcompat.methodgen.DynamicBridge.hookMethod(DynamicBridge.java:62)
> > at de.robv.android.xposed.XposedBridge.hookMethodNative(XposedBridge.java:275)
> > at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:181)
> > at de.robv.android.xposed.XposedBridge.hookAllConstructors(XposedBridge.java:237)
> > at com.crystal.chat.hook.SafetyHooker.(SafetyHooker.java:28)
> > at com.crystal.chat.hook.MainHookApplication.attachBaseContext(MainHookApplication.java:61)
> > at android.app.Application.attach(Application.java:212)
> > at android.app.Instrumentation.newApplication(Instrumentation.java:1121)
> > at android.app.LoadedApk.makeApplication(LoadedApk.java:1061)
> > at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5842)
> > at android.app.ActivityThread.access$1100(ActivityThread.java:199)
> > at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
> > at android.os.Handler.dispatchMessage(Handler.java:106)
> > at android.os.Looper.loop(Looper.java:193)
> > at android.app.ActivityThread.main(ActivityThread.java:6669)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> > Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.crystal.chat-6Xom5tpjwmxgaBsFLCTcEA==/base.apk"],nativeLibraryDirectories=[/data/app/com.crystal.chat-6Xom5tpjwmxgaBsFLCTcEA==/lib/x86, /data/app/com.crystal.chat-6Xom5tpjwmxgaBsFLCTcEA==/base.apk!/lib/x86, /system/lib]]] couldn't find "libsandhook.so"
> > at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
> > at java.lang.System.loadLibrary(System.java:1669)
> > at com.swift.sandhook.SandHookConfig$1.loadLib(SandHookConfig.java:22)
> > at com.swift.sandhook.SandHook.(SandHook.java:48)
> > at com.swift.sandhook.SandHook.is64Bit(Native Method)
> > at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.(HookStubManager.java:43)
> > at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.getHookMethodEntity(HookStubManager.java:64)
> > at com.swift.sandhook.xposedcompat.methodgen.DynamicBridge.hookMethod(DynamicBridge.java:62)
> > at de.robv.android.xposed.XposedBridge.hookMethodNative(XposedBridge.java:275)
> > at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:181)
> > at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:187)
> > at com.crystal.chat.hook.MainHookApplication.attachBaseContext(MainHookApplication.java:47)
> > at android.app.Application.attach(Application.java:212) 
> > at android.app.Instrumentation.newApplication(Instrumentation.java:1121) 
> > at android.app.LoadedApk.makeApplication(LoadedApk.java:1061) 
> > at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5842) 
> > at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
> > at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
> > at android.os.Handler.dispatchMessage(Handler.java:106) 
> > at android.os.Looper.loop(Looper.java:193) 
> > at android.app.ActivityThread.main(ActivityThread.java:6669) 
> > at java.lang.reflect.Method.invoke(Native Method) 
> > at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

1. 暂不支持 X86
2. 没反应 SandHookConfig.DEBUG = true 试试，这个一定要在最前面正确配置，否则很可能无法生效，SandHookConfig.DEBUG 跟你的 app 是否 debuggable 保持一致

**Comment by Anzhi-Meiying** [comment]
@ganyao114 非常感谢，请问ApplicationInfo.class这个类无法hook是bug吗，我hook之后没有反应，但是epic可以hook掉

**Comment by ganyao114** [comment]
> @ganyao114 非常感谢，请问ApplicationInfo.class这个类无法hook是bug吗，我hook之后没有反应，但是epic可以hook掉

应该是可以 Hook 的，你再自查一下

**Comment by Anzhi-Meiying** [comment]
@ganyao114 又遇到了问题，方便加一下微信或者qq吗
![Uploading image.png…]()

**Comment by ganyao114** [comment]
> @ganyao114 又遇到了问题，方便加一下微信或者qq吗

qq 939543405
