### ISSUE TITLE
java.lang.NoSuchMethodException: generateProxy

### ISSUE THREAD

**Issue by douniwan5788** [ganyao114/SandHook#20]
从 3.6.0 版本开始报错
```
06-25 17:06:58.003 30430-30469/? W/System.err: java.lang.NoSuchMethodException: generateProxy [class java.lang.String, class [Ljava.lang.Class;, class java.lang.ClassLoader, class [Ljava.lang.reflect.Method;, class [[Ljava.lang.Class;]
06-25 17:06:58.003 30430-30469/? W/System.err:     at java.lang.Class.getMethod(Class.java:664)
06-25 17:06:58.003 30430-30469/? W/System.err:     at java.lang.Class.getDeclaredMethod(Class.java:626)
06-25 17:06:58.003 30430-30469/? W/System.err:     at com.swift.sandhook.wrapper.StubMethodsFactory.<clinit>(StubMethodsFactory.java:15)
06-25 17:06:58.003 30430-30469/? W/System.err:     at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.getStubMethodPair(HookStubManager.java:176)
06-25 17:06:58.003 30430-30469/? W/System.err:     at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.getHookMethodEntity(HookStubManager.java:104)
06-25 17:06:58.003 30430-30469/? W/System.err:     at com.swift.sandhook.xposedcompat.methodgen.DynamicBridge.hookMethod(DynamicBridge.java:63)
06-25 17:06:58.003 30430-30469/? W/System.err:     at de.robv.android.xposed.XposedBridge.hookMethodNative(XposedBridge.java:275)
06-25 17:06:58.003 30430-30469/? W/System.err:     at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:181)
```

ps:希望在bintray上传时能加上 VCS Tag，这样方便定位代码版本

**Comment by ganyao114** [comment]
这个日志没有关系
