### ISSUE TITLE
JNI DETECTED ERROR IN APPLICATION: use of invalid jobject xxxx

### ISSUE THREAD

**Issue by xiaobaiyey** [ganyao114/SandHook#31]
android 6.0 nexus 6p
hook com.android.internal.os.ZygoteInit.handleSystemServerProcess ,
crash log
```

08-28 00:35:06.421 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: use of invalid jobject 0x7fafddb180
08-28 00:35:06.421 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410]     from void com.android.internal.os.ZygoteInit.handleSystemServerProcess!(com.android.internal.os.ZygoteConnection$Arguments)
08-28 00:35:06.421 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410] "main" prio=5 tid=1 Runnable
08-28 00:35:06.421 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410]   | group="main" sCount=0 dsCount=0 obj=0x73ea0878 self=0x7fb003ba00
08-28 00:35:06.422 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410]   | sysTid=4220 nice=0 cgrp=default sched=0/0 handle=0x7fb3584fe8
08-28 00:35:06.422 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410]   | state=R schedstat=( 35969742 621719 21 ) utm=0 stm=3 core=4 HZ=100
08-28 00:35:06.422 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410]   | stack=0x7fc70be000-0x7fc70c0000 stackSize=8MB
08-28 00:35:06.422 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410]   | held mutexes= "mutator lock"(shared held)
08-28 00:35:06.422 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410]   native: #00 pc 000000000023a108  /system/lib64/libart.so (???)
08-28 00:35:06.422 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410]   native: #01 pc 00000000002092c8  /system/lib64/libart.so (???)
08-28 00:35:06.422 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410]   native: #02 pc 00000000000bd730  /system/lib64/libart.so (???)
08-28 00:35:06.422 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410]   native: #03 pc 00000000000be104  /system/lib64/libart.so (???)
08-28 00:35:06.422 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410]   native: #04 pc 00000000002096f0  /system/lib64/libart.so (???)
08-28 00:35:06.422 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410]   native: #05 pc 00000000000f72bc  /system/lib64/libart.so (???)
08-28 00:35:06.422 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410]   native: #06 pc 0000000000059798  /data/local/tmp/libsandhook.so (_ZN7_JNIEnv21SetObjectArrayElementEP13_jobjectArrayiP8_jobject+72)
08-28 00:35:06.422 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410]   native: #07 pc 00000000000573c8  /data/local/tmp/libsandhook.so (_ZN20QuickArgumentBuilder12AppendObjectEP8_jobject+152)
08-28 00:35:06.422 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410]   native: #08 pc 0000000000056a9c  /data/local/tmp/libsandhook.so (_Z16FFIJniDispatcherP10FFIClosurePvPS1_S1_+588)
08-28 00:35:06.422 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410]   native: #09 pc 000000000006da5c  /data/local/tmp/libsandhook.so(_Z13FFIDispatcherP7ffi_cifPvPS1_S1_+120)
08-28 00:35:06.422 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410]   native: #10 pc 000000000007fce0  /data/local/tmp/libsandhook.so (ffi_closure_SYSV_inner+912)
08-28 00:35:06.422 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410]   native: #11 pc 0000000000080730  /data/local/tmp/libsandhook.so (ffi_closure_SYSV+48)
08-28 00:35:06.422 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410]   native: #12 pc 0000000000008e4c  /data/dalvik-cache/arm64/system@framework@waa.jar@classes.dex (Java_com_android_internal_os_ZygoteInit_handleSystemServerProcess__Lcom_android_internal_os_ZygoteConnection_00024Arguments_2+128)
08-28 00:35:06.422 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410]   at com.android.internal.os.ZygoteInit.handleSystemServerProcess!(Native method)
08-28 00:35:06.422 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410]   at com.android.internal.os.ZygoteInit.startSystemServer(ZygoteInit.java:545)
08-28 00:35:06.422 4220-4220/? A/art: art/runtime/java_vm_ext.cc:410]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
```

Maybe getting the parameter error
Will crash when calling AppendObject
```
AppendObject: Append value:0x7fafddb180
```

**Comment by xiaobaiyey** [comment]
建议先不要用 xposedcompat_new模块，这个模块坑有点多。
