### ISSUE TITLE
android  10.0 

### ISSUE THREAD

**Issue by 850636558myj** [ganyao114/SandHook#42]
android  10.0 支持么？

**Comment by ganyao114** [comment]
支持

**Comment by 850636558myj** [comment]
@ganyao114   我hook  线程构造函数失败了 
android 8.0 
2019-12-16 19:34:03.263 6528-6662/com.uc.vmate E/zygote64: Exception creating thread peer:
2019-12-16 19:34:03.263 6528-6662/com.uc.vmate E/zygote64: java.lang.NullPointerException: null receiver
2019-12-16 19:34:03.263 6528-6662/com.uc.vmate E/zygote64:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2019-12-16 19:34:03.263 6528-6662/com.uc.vmate E/zygote64:     at java.lang.Object com.swift.sandhook.SandHook.callOriginMethod(boolean, java.lang.reflect.Member, java.lang.reflect.Method, java.lang.Object, java.lang.Object[]) (SandHook.java:176)
2019-12-16 19:34:03.263 6528-6662/com.uc.vmate E/zygote64:     at java.lang.Object com.swift.sandhook.SandHook.callOriginMethod(java.lang.reflect.Member, java.lang.Object, java.lang.Object[]) (SandHook.java:143)
2019-12-16 19:34:03.263 6528-6662/com.uc.vmate E/zygote64:     at long com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(int, com.swift.sandhook.xposedcompat.hookstub.CallOriginCallBack, long[]) (HookStubManager.java:305)
2019-12-16 19:34:03.263 6528-6662/com.uc.vmate E/zygote64:     at long com.swift.sandhook.xposedcompat.hookstub.MethodHookerStubs64.stub_hook_1(long, long, long, long, long) (MethodHookerStubs64.java:746)

调用方法如下：

```

    public static void initHook(String commonInfo, String path, Application application) {
        mCommonInfo = commonInfo;
        try {
            //setup for xposed
            XposedCompat.cacheDir = new File(path);
            XposedCompat.context = application;
            XposedCompat.classLoader = application.getClassLoader();
            XposedCompat.isFirstApplication = ProcessUtil.isMainProcess();
            hookThread();
            hookExecutors();
        } catch (Throwable t) {
            // ignore it   适配性机型  比如android10 无法hook
        }
    }

    private static void hookThread() {
        XposedBridge.hookAllConstructors(Thread.class, new XC_MethodHook() {
            @Override
            protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                super.beforeHookedMethod(param);
                wormHandler.post(threadRunnable);
            }

            @Override
            protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                super.afterHookedMethod(param);
            }
        });
    }

```

**Comment by 850636558myj** [comment]
implementation 'com.swift.sandhook:hooklib:3.4.0'
    implementation 'com.swift.sandhook:xposedcompat:3.4.0'

**Comment by ganyao114** [comment]
最新版 4.1.5

**Comment by 850636558myj** [comment]
SandHook.disableVMInline();
            SandHook.tryDisableProfile(application.getPackageName());
            if (SandHookConfig.SDK_INT >= Build.VERSION_CODES.P) {
                SandHook.passApiCheck();
            }


请问这些必须调用么

**Comment by 850636558myj** [comment]
@ganyao114

**Comment by ganyao114** [comment]
不是
        SandHook.disableVMInline();
        SandHook.tryDisableProfile(application.getPackageName());

这两个建议使用

**Comment by 850636558myj** [comment]
2019-12-16 20:38:06.691 13835-13836/? E/SandXposed: java.lang.NullPointerException: null receiver
        at java.lang.reflect.Method.invoke(Native Method)
        at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:185)
        at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:163)
        at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:299)


还是崩溃

**Comment by 850636558myj** [comment]
// 目前只支持4.4 - 10.0
    public static void initHook(String commonInfo, String path, Application application) {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.KITKAT) {
            return;
        }

        mCommonInfo = commonInfo;
        try {
            SandHook.disableVMInline();
            SandHook.tryDisableProfile(application.getPackageName());
            if (SandHookConfig.SDK_INT >= Build.VERSION_CODES.P) {
                SandHook.passApiCheck();
            }
            //setup for xposed
            XposedCompat.cacheDir = new File(path);
            XposedCompat.context = application;
            XposedCompat.classLoader = application.getClassLoader();
            XposedCompat.isFirstApplication = ProcessUtil.isMainProcess();
            hookThread();
            hookExecutors();
        } catch (Throwable t) {
            // ignore it   适配性机型  比如android10 无法hook
        }
    }

    private static void hookThread() {
        XposedBridge.hookAllConstructors(Thread.class, new XC_MethodHook() {
            @Override
            protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                super.beforeHookedMethod(param);
                wormHandler.post(threadRunnable);
            }

            @Override
            protected void afterHookedMethod(MethodHookParam param) throws Throwable {
                super.afterHookedMethod(param);
            }
        });
    }

**Comment by 850636558myj** [comment]
implementation 'com.swift.sandhook:hooklib:4.1.5'
    implementation 'com.swift.sandhook:xposedcompat:4.1.5'


使用最新版还是空指针崩溃   @ganyao114

**Comment by 850636558myj** [comment]
2019-12-16 20:44:01.975 15071-15200/com.uc.vmate E/SandXposed: java.lang.NullPointerException: null receiver
        at java.lang.reflect.Method.invoke(Native Method)
        at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:185)
        at com.swift.sandhook.SandHook.callOriginMethod(SandHook.java:163)
        at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:299)
        at com.swift.sandhook.xposedcompat.hookstub.MethodHookerStubs64.stub_hook_1(MethodHookerStubs64.java:746)
2019-12-16 20:44:01.975 15071-15200/com.uc.vmate E/com.uc.vmate: Exception creating thread peer:
2019-12-16 20:44:01.975 15071-15200/com.uc.vmate E/com.uc.vmate: java.lang.NullPointerException: null receiver
2019-12-16 20:44:01.975 15071-15200/com.uc.vmate E/com.uc.vmate: (Throwable with no stack trace)

**Comment by ganyao114** [comment]
已修复
