### ISSUE TITLE
originMethod NPE

### ISSUE THREAD

**Issue by taiyang5946** [ganyao114/SandHook#49]
`Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.reflect.Member.getModifiers()' on a null object reference
	at com.swift.sandhook.SandHook.callOriginMethod(SpiderMan.java:175)
	at com.swift.sandhook.SandHook.callOriginMethod(SpiderMan.java:165)
	at com.swift.sandhook.xposedcompat.hookstub.HookStubManager.hookBridge(HookStubManager.java:372)
	at SandHookerNew_7hrlnqe1khj90va5eljsf5sh69.hook(Unknown Source:58)`

**Comment by ganyao114** [comment]
如何复现
