### ISSUE TITLE
SandVXposed-beta_3.apk在mumu模拟器运行apk异常

### ISSUE THREAD

**Issue by Jimmy0806** [ganyao114/SandHook#55]
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.swift.sandhook.utils.ReflectionUtils.<clinit>(ReflectionUtils.java:28)
        at com.swift.sandhook.utils.ReflectionUtils.passApiCheck(ReflectionUtils.java)
        at com.swift.sandhook.SandHook.passApiCheck(SandHook.java:322)
        at com.lody.virtual.sandxposed.SandXposed.init(SandXposed.java:28)
        at io.virtualapp.VApp.attachBaseContext(VApp.java:39)
        at android.app.Application.attach(Application.java:187)
        at android.app.Instrumentation.newApplication(Instrumentation.java:997)
        at android.app.Instrumentation.newApplication(Instrumentation.java:981)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:573)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4752)
        at android.app.ActivityThread.-wrap1(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
     Caused by: java.lang.NoSuchMethodException: setHiddenApiExemptions [class [Ljava.lang.String;]
        at java.lang.Class.getMethod(Class.java:624)
        at java.lang.Class.getDeclaredMethod(Class.java:586)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.swift.sandhook.utils.ReflectionUtils.<clinit>(ReflectionUtils.java:28) 
        at com.swift.sandhook.utils.ReflectionUtils.passApiCheck(ReflectionUtils.java) 
        at com.swift.sandhook.SandHook.passApiCheck(SandHook.java:322) 
        at com.lody.virtual.sandxposed.SandXposed.init(SandXposed.java:28) 
        at io.virtualapp.VApp.attachBaseContext(VApp.java:39) 
        at android.app.Application.attach(Application.java:187) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:997) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:981) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:573) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4752) 
        at android.app.ActivityThread.-wrap1(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1414) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5539) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)

**Comment by Jimmy0806** [comment]
demo在mumu模拟器（Android 6.0）也是会闪退，mumu模拟器正常是支持运行armv7的应用的
、
`06-18 14:43:17.209 7084-7084/? W/art: Unexpected CPU variant for X86 using defaults: x86
06-18 14:43:17.236 7084-7091/? E/art: Failed sending reply to debugger: Broken pipe
06-18 14:43:17.298 7084-7084/? W/SandHook-Native: JNI Loaded
06-18 14:43:17.401 7084-7084/? W/SandHook-Native: can not inline due to origin code is too small(size is 0)
06-18 14:43:17.462 7084-7084/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
    
    --------- beginning of crash
06-18 14:43:17.477 7084-7084/? A/libc: Fatal signal 11 (SIGSEGV), code 128, fault addr 0x0 in tid 7084 (.swift.sandhook)
06-18 14:43:17.578 246-246/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-18 14:43:17.578 246-246/? A/DEBUG: Build fingerprint: 'OnePlus/OnePlus2/OnePlus2:6.0.1/MMB29M/1447841200:user/release-keys'
06-18 14:43:17.578 246-246/? A/DEBUG: Revision: '0'
06-18 14:43:17.578 246-246/? A/DEBUG: ABI: 'x86'
06-18 14:43:17.578 246-246/? A/DEBUG: pid: 7084, tid: 7084, name: .swift.sandhook  >>> com.swift.sandhook <<<
06-18 14:43:17.578 246-246/? A/DEBUG: signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0
06-18 14:43:17.581 246-246/? A/DEBUG:     eax 70981de0  ebx 0000000c  ecx 12c295d0  edx 00000000
06-18 14:43:17.581 246-246/? A/DEBUG:     esi 719f2a21  edi bf8a658c
06-18 14:43:17.581 246-246/? A/DEBUG:     xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
06-18 14:43:17.581 246-246/? A/DEBUG:     eip 733ff75e  ebp bf8a643c  esp bf8a642c  flags 00210283
06-18 14:43:17.582 246-246/? A/DEBUG: backtrace:
06-18 14:43:17.582 246-246/? A/DEBUG:     #00 pc 0000075e  /system/framework/x86/boot.oat (offset 0x28c2000)
06-18 14:43:17.582 246-246/? A/DEBUG:     #01 pc 000b64ff  <unknown>
06-18 14:43:17.582 246-246/? A/DEBUG:     #02 pc 007fb493  [stack]
06-18 14:43:17.627 246-246/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_05`

**Comment by Jimmy0806** [comment]
sandhook demo在红米android 6.0系统也直接崩溃
`    --------- beginning of crash
06-18 17:34:22.159 21292-21309/com.swift.sandhook E/AndroidRuntime: FATAL EXCEPTION: Thread-1204
    Process: com.swift.sandhook, PID: 21292
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.StringBuilder java.lang.StringBuilder.append(java.lang.Object)' on a null object reference
        at com.swift.sandhook.MainActivity$3.run(MainActivity.java:79)
        at java.lang.Thread.run(Thread.java:818)`

**Comment by Jimmy0806** [comment]
测试了一下，好像这个sandhook demo在国内各个主流的模拟器上都是直接崩溃，yahfa也一样

**Comment by hwangjr** [comment]
最新版本 sandvexposed 使用 红米 miui 10.2 也闪退
```

08-25 10:45:41.452 12461-12461/? W/ResourceType: No package identifier when getting name for resource number 0x00000000
08-25 10:45:41.469 12461-12461/? I/MultiDex: VM with version 2.1.0 has multidex support
08-25 10:45:41.469 12461-12461/? I/MultiDex: Installing application
08-25 10:45:41.469 12461-12461/? I/MultiDex: VM has multidex support, MultiDex support library is disabled.
08-25 10:45:41.496 12461-12461/? W/SandHook-Native: JNI Loaded
08-25 10:45:41.513 12461-12461/? D/dlopen: f4927000-f4d5f000 r-xp 00000000 fd:00 2240                               /system/lib/libart.so
08-25 10:45:41.513 12461-12461/? D/SandHook-Native: get module base /system/lib/libart.so: 4103237632
08-25 10:45:41.514 12461-12461/? D/SandHook-Native: find /system/lib/libart.so: eb001
    
    
    --------- beginning of crash
08-25 10:45:41.516 12461-12461/? A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0xab7dd3b0 in tid 12461 (app.sandvxposed)
08-25 10:45:41.568 697-697/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-25 10:45:41.568 697-697/? A/DEBUG: Build fingerprint: 'Xiaomi/rolex/rolex:6.0.1/MMB29M/V10.2.2.0.MCCCNXM:user/release-keys'
08-25 10:45:41.568 697-697/? A/DEBUG: Revision: '0'
08-25 10:45:41.568 697-697/? A/DEBUG: ABI: 'arm'
08-25 10:45:41.568 697-697/? A/DEBUG: pid: 12461, tid: 12461, name: app.sandvxposed  >>> io.virtualapp.sandvxposed <<<
08-25 10:45:41.568 697-697/? A/DEBUG: signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xab7dd3b0
08-25 10:45:41.580 697-697/? A/DEBUG:     r0 ab76fb88  r1 ab76fb88  r2 ab7dd3b0  r3 00000002
08-25 10:45:41.580 697-697/? A/DEBUG:     r4 00000008  r5 f4a34a05  r6 ab551130  r7 ffc83dd8
08-25 10:45:41.580 697-697/? A/DEBUG:     r8 ab55d6c4  r9 ab55d638  sl 00000000  fp ffc84054
08-25 10:45:41.580 697-697/? A/DEBUG:     ip f6e165dc  sp ffc83cd0  lr ef9372a9  pc ab7dd3b0  cpsr 20070010
08-25 10:45:41.582 697-697/? A/DEBUG: backtrace:
08-25 10:45:41.582 697-697/? A/DEBUG:     #00 pc 002973b0  [heap]
08-25 10:45:41.582 697-697/? A/DEBUG:     #01 pc 0004b2a7  /data/app/io.virtualapp.sandvxposed-1/lib/arm/libsandhook-native.so (_ZN8SandHook7Decoder12Arm32Decoder11DisassembleEPvjRNS0_11InstVisitorEb+1510)
08-25 10:45:41.582 697-697/? A/DEBUG:     #02 pc 0004d71d  /data/app/io.virtualapp.sandvxposed-1/lib/arm/libsandhook-native.so (_ZN8SandHook3Asm15CodeRelocateA328RelocateEPvjS2_+228)
08-25 10:45:41.582 697-697/? A/DEBUG:     #03 pc 0004b96d  /data/app/io.virtualapp.sandvxposed-1/lib/arm/libsandhook-native.so (_ZN8SandHook4Hook22InlineHookArm32Android4HookEPvS2_+412)
08-25 10:45:41.583 697-697/? A/DEBUG:     #04 pc 0003c28f  /data/app/io.virtualapp.sandvxposed-1/lib/arm/libsandhook-native.so (SandInlineHook+42)
08-25 10:45:41.583 697-697/? A/DEBUG:     #05 pc 0001750f  /data/app/io.virtualapp.sandvxposed-1/lib/arm/libsandhook.so (hookClassInit+54)
08-25 10:45:41.583 697-697/? A/DEBUG:     #06 pc 0001588b  /data/app/io.virtualapp.sandvxposed-1/lib/arm/libsandhook.so (Java_com_swift_sandhook_SandHook_initForPendingHook+62)
08-25 10:45:41.583 697-697/? A/DEBUG:     #07 pc 00b5c9d5  /data/app/io.virtualapp.sandvxposed-1/oat/arm/base.odex (offset 0x82b000)
08-25 10:45:41.753 1504-1524/? I/Timeline: Timeline: App_transition_stopped time:1045749100
08-25 10:45:41.754 697-697/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_09
08-25 10:45:41.754 697-697/? E/DEBUG: AM write failed: Broken pipe
08-25 10:45:41.755 3247-3273/? D/PowerKeeper.Event: notifyAMCrash packageName: 0, pid:1504
    
    --------- beginning of system
08-25 10:45:41.759 1504-12475/? W/ActivityManager:   Force finishing activity io.virtualapp.sandvxposed/io.virtualapp.splash.SplashActivity
08-25 10:45:41.764 1504-12475/? D/ActivityTrigger: ActivityTrigger activityPauseTrigger 
```
