### ISSUE TITLE
安卓12 崩溃

### ISSUE THREAD

**Issue by GameMario123** [ganyao114/SandHook#89]
W/System.err: java.lang.NoSuchMethodException: java.lang.reflect.Proxy.generateProxy [class java.lang.String, class [Ljava.lang.Class;, class java.lang.ClassLoader, class [Ljava.lang.reflect.Method;, class [[Ljava.lang.Class;]
W/System.err:     at java.lang.Class.getMethod(Class.java:2103)
W/System.err:     at java.lang.Class.getDeclaredMethod(Class.java:2081)
W/System.err:     at com.swift.sandhook.wrapper.StubMethodsFactory.<clinit>(StubMethodsFactory.java:15)
W/System.err:     at com.swift.sandhook.wrapper.StubMethodsFactory.getStubMethod(Unknown Source:0)
W/System.err:     at com.swift.sandhook.wrapper.HookWrapper.fillBackupMethod(HookWrapper.java:71)
W/System.err:     at com.swift.sandhook.wrapper.HookWrapper.addHookClass(HookWrapper.java:43)
W/System.err:     at com.swift.sandhook.wrapper.HookWrapper.addHookClass(HookWrapper.java:33)
W/System.err:     at com.swift.sandhook.wrapper.HookWrapper.addHookClass(HookWrapper.java:28)
W/System.err:     at com.swift.sandhook.SandHook.addHookClass(SandHook.java:69)
W/System.err:     at com.my.cp.hook.MyHookManager.initHook(MyHookManager.kt:37)
W/System.err:     at com.my.cp.MainApplication.onCreate(MainApplication.java:121)
W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6728)
W/System.err:     at android.app.ActivityThread.access$1500(ActivityThread.java:247)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2057)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err:     at android.os.Looper.loopOnce(Looper.java:201)
W/System.err:     at android.os.Looper.loop(Looper.java:288)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7842)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

并没有抓到 崩溃的日志，只是看到这条日志了。手机是 Pixel 3，今天升级的安卓12。
谢谢了。

**Comment by 15198184721** [comment]
我也遇到了。Android12上必崩溃。求解决办法

**Comment by dqzg12300** [comment]
一样碰到这个问题，求解决

**Comment by xjohjrdy** [comment]
+1

**Comment by lwannn** [comment]
+1111
